version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10

  jobs:
    pre_build:
      - "jupyter-book config sphinx doc/"


conda:
  environment: environment.yml

sphinx:
  builder: html
  fail_on_warning: true
  configuration: doc/_config.yml

